language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script: yarn start
before_deploy: yarn global add now
deploy:
  - provider: script
    script: now --token $NOW_TOKEN --public
    skip_cleanup: true
    on:
      all_branches: true
      master: true